### ISSUE TITLE
Cache tra twin

### ISSUE THREAD

**Issue by SamueleColombo** [HamtaroAndFriends/ASD#4]
Quando creo un Twin ho sempre delle informazioni contenute nell'automa di partenza. Bisogna ricopiarle sempre?

**Comment by fededanesi** [comment]
a me non sembra che vengano utilizzate dagli algoritmi che lavorano sui Twin
Il 15 mar 2016 22:36, "Samuele Colombo" notifications@github.com ha
scritto:

> Quando creo un Twin ho sempre delle informazioni contenute nell'automa di
> partenza. Bisogna ricopiarle sempre?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/HamtaroAndFriends/ASD/issues/4

## 

Informativa sulla Privacy: http://www.unibs.it/node/8155
